# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

inherit_from: .rubocop_todo.yml

AllCops:
  RubyInterpreters:
    - ruby
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'bin/*'

Metrics/AbcSize:
  Max: 37

Metrics/BlockLength:
  Max: 36
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 44

Metrics/PerceivedComplexity:
  Max: 7

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
